services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_with_docs_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./chroma:/app/chroma
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  frontend:
    build:
      context: ./frontend
    container_name: chat_with_docs_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
    depends_on:
      api:
        condition: service_healthy
    environment:
      - API_URL=http://api:8000/api/v1